### ISSUE TITLE
Избавиться от верхнеуровненого каталога WebApp

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#1]
Нужно его содержимое поместить в корень git-репозитория.

**Comment by cssru** [comment]
если сделать это на github, IDEA потом догадается или создаст еще одно дерево папок локально?

**Comment by php-coder** [comment]
Не знаю, надо проверять. Если что, просто проимпортируете проект в IDEA еще раз и она должна будет понять.

**Comment by cssru** [comment]
чето пока не приходит в голову как перенести. git mv ?

**Comment by php-coder** [comment]
Да. Попробуйте `git mv WebApp/* .`

**Comment by cssru** [comment]
нет, так не получается:
fatal: исходный каталог пуст, source=WebApp/target, destination=target

**Comment by php-coder** [comment]
А, ну да. Потому что там `target/`. Тогда до `git mv` нужно было сделать `mvn clean`.
