### ISSUE TITLE
Удалить и добавить в .gitignore .iml файл

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#2]
Файл с настройками для IDEA (или любого другого редактора) не нужно публиковать в репозитории.

**Comment by cssru** [comment]
удалил и заигнорил

**Comment by php-coder** [comment]
Вы можете в комментарии к коммиту добавлять фразу типа "Fix #NN", где NN номер тикета и тогда GitHub автоматически закроет этот тикет и добавит в него ссылку на соответствующий коммит.

**Comment by cssru** [comment]
Fix #2

**Comment by php-coder** [comment]
Вижу, что забыл добавить в `.gitignore`. Также добавь туда `.idea` и `target`
