### ISSUE TITLE
Использовать BOM для Spring и Spring Security

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#4]
Чтобы версии артефакт ов были всегда одной версии и не было мешанины советую использовать BOM артефакты.

См:
- http://docs.spring.io/spring/docs/4.1.x/spring-framework-reference/html/overview.html#overview-maven-bom
- http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#maven-bom

**Comment by cssru** [comment]
добавил
 <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-bom</artifactId>
                <version>4.0.2.RELEASE</version>
            </dependency>

получил:
Some problems were encountered while processing the POMs: [ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-web:jar is missing. @ line 120, column 21 [ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-core:jar is missing. @ line 124, column 21 [ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-config:jar is missing. @ line 128, column 21 [ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-taglibs:jar is missing. @ line 132, column 21

Чего-то я не знаю, по ходу...

**Comment by cssru** [comment]
ВОпрос снят.
Забыл про 
 <type>pom</type>
 <scope>import</scope>
