### ISSUE TITLE
Обновить Jetty плагин

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#5]
Возьмите версию посвежее, но только из стабильной ветки.

См. http://www.eclipse.org/jetty/documentation/current/jetty-maven-plugin.html

**Comment by cssru** [comment]
Обновил
Fix #5

**Comment by php-coder** [comment]
Этот комментарий нужно указывать в описании к коммиту, когда коммитите.

**Comment by php-coder** [comment]
8.1.16 это трехлетнее старье :) Я неспроста ссылочку дал. Возьмите, хотя бы из ветки 9.2

**Comment by cssru** [comment]
http://mvnrepository.com/artifact/org.mortbay.jetty/jetty-maven-plugin - не, не трехлетнее, сентябрь 2014 ))
Но в репе это самое свежее, странно, откуда 9.2?

**Comment by php-coder** [comment]
Потому что они переехали на другой `groupId`/`artifactId`

**Comment by cssru** [comment]
угу, нашел 
http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-maven-plugin/9.3.3.v20150827

**Comment by cssru** [comment]
Слава, у меня получилось с Fix ! ))

**Comment by php-coder** [comment]
Ага, отлично!

**Comment by cssru** [comment]
Зашибись, теперь при запуске
[INFO] The plugin 'org.apache.maven.plugins:maven-jetty-plugin' does not exist or no valid version could be found
IDE показывает, что все норм
