### ISSUE TITLE
Spring Security: включить защиту от CSRF

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#6]
Сейчас в конфигурации Spring Security защита от CSRF отключена. Нужно включить.

**Comment by cssru** [comment]
http.csrf().disable() - разве это не включает защиту?

**Comment by php-coder** [comment]
Нет, защита от CSRF в последних версиях включена по умолчанию, а `csrf().disable()` ее как раз отключает (потому что здесь disable, а не enable).

**Comment by cssru** [comment]
Хм, а я думал, что disable как раз запрещает атаки ))

**Comment by cssru** [comment]
http // убрал запрет csrf
                .authorizeRequests()
                .antMatchers("*").denyAll() // так можно запретить скачивание /webapp/\* ?
                .antMatchers("/resources/**", "/**").permitAll()
                .antMatchers("/", "/index").permitAll()
                .antMatchers("/homo.add").authenticated();

**Comment by php-coder** [comment]
> .antMatchers("_").denyAll() // так можно запретить скачивание /webapp/_ ?

Нет. Вы не с той стороны заходите. Скачивание файлов из /webapp сделано намеренно -- туда вы будете складывать, например, CSS/JS-файлы и другие статические ресурсы.

Вы можете использовать каталог `webapp/WEB-INF`, который недоступен пользователю или, что лучше, складывать в `src/main/resources`, к остальным ресурсам (а если оттуда не видит, то это уже другая история и нужно разбираться отдельно).

**Comment by cssru** [comment]
Где ищет ресурсы ClassPathResource?

**Comment by php-coder** [comment]
> Где ищет ресурсы ClassPathResource?

В classpath-е приложения. Извиняюсь, за капитанство :)

**Comment by cssru** [comment]
Хм...тимлид - не капитан. Минимум подполковник ))
http
                .authorizeRequests()
                .antMatchers("_").denyAll()
                .antMatchers("/resources/_.sql").denyAll() // по идее, нужно же запретить?
                .antMatchers("/resources/**", "/**").permitAll()
                .antMatchers("/", "/index").permitAll()
                .antMatchers("/homo.add").authenticated();
Перенес скрипт, так лучше?

**Comment by cssru** [comment]
Как настроить classpath в IDEA?

**Comment by php-coder** [comment]
> Как настроить classpath в IDEA?

Не знаю, никогда не прихолилось настраивать, т.к. при работе с Maven проектом IDEA  добавляет все зависимости в classpath.

Да и зачем тебе это могло понадобиться?

**Comment by php-coder** [comment]
> .antMatchers("/resources/.sql").denyAll() // по идее, нужно же запретить?

Да, но не так :) Попробую записать себе куда-нибудь, чтобы написать/нарисовать схему с объяснением что тут и как работает.

**Comment by cssru** [comment]
@Bean
    public DataSource dataSource() {
        EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
        EmbeddedDatabase database = builder
                .setName("test")
                .setType(EmbeddedDatabaseType.H2)
                .addScript("create_db.sql") // вот тут  - если не положить в webapp, то получаю FileNotFoundException
                .build();
        return database;
    }

**Comment by cssru** [comment]
EmbeddedDatabase грузит ресурсы через ClassPathResource и не находит файл в /resources

**Comment by php-coder** [comment]
Во-первых, это уже не относится к тикету про Spring Security.
Во-вторых, у меня все работало, я проверял.
В-третьих, хорошо бы привести stacktrace с сообщением об ошибке.

**Comment by php-coder** [comment]
P.S. 

> /resources

Файл должен быть в репозитории в каталоге `src/main/resources`.
О каком `/resources` ты говоришь?

**Comment by cssru** [comment]
src/main/resources о нем

**Comment by cssru** [comment]
после "включения" защиты от csrf:
Problem accessing /WebApp/j_spring_security_check. Reason:
    Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.

**Comment by php-coder** [comment]
Да-да, еще и логаут потом нужно будет поправить. Я знаю :) Нужно, чтобы и ты разобрался.

**Comment by cssru** [comment]
Где лучше почитать?

**Comment by php-coder** [comment]
В доке по Spring Security должно быть. В блоге еще у них было. Ну и про сам CSRF тоже нужно прочитать, если еще не в курсе.

**Comment by php-coder** [comment]
> > .antMatchers("/resources/.sql").denyAll() // по идее, нужно же запретить?
> > Да, но не так :) Попробую записать себе куда-нибудь, чтобы написать/нарисовать схему с объяснением что тут и как работает.

Сам не добрался, но попросил хорошего знакомого. Вот что получилось: http://flexjoy.blogspot.ru/2015/09/blog-post_19.html (если будут комментарии/улучшения к статье, то пиши им в блог сразу).

Надеюсь, что после прочтения станет чуть-чуть понятнее структура мавена/WAR-ника. После этого посмотри на свои настройки Spring Security и попробуй понять что не так.
