### ISSUE TITLE
Добавить файл c описанием проекта

### ISSUE THREAD

**Issue by php-coder** [cssru/WebAppTest#7]
Необходимо добавить `README.md` файл и положить его в корень проекта. В нем должно быть описание проекта, как его собрать/запустить и под каким пользователем/паролем заходить.

**Comment by cssru** [comment]
По аглицки описание или на родном? )

**Comment by php-coder** [comment]
As you wish :-)

**Comment by cssru** [comment]
I wish chinese, but I can't :-)

**Comment by cssru** [comment]
Я так понимаю, что начать ридми словами:
Hello! My name is Serjozha!
- не самое лучшее решение.
  Будем плагиатить...

**Comment by cssru** [comment]
Мдяя.. с английским у меня тоже проблемы ((
